/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\zuvy-baby-with-hair1.glb -T 
Files: .\zuvy-baby-with-hair1.glb [1.03MB] > D:\Test Project\zuvara-frontend\public\models\zuvy-baby-with-hair1-transformed.glb [138.87KB] (87%)
*/

import React, { useEffect, useRef } from 'react'
import { useAnimations, useFBX, useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    eyebrow002: THREE.Mesh
    zuvera_body_v008001: THREE.Mesh
    diaper002: THREE.Mesh
    domyEyeBall_L_upHeadBase002: THREE.Mesh
    domyEyeBall_R_upHeadBase002: THREE.Mesh
    Object_3001: THREE.Mesh
  }
  materials: {
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['diaper-texture']: THREE.MeshStandardMaterial
    eyeColor: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    BodyB_mat: THREE.MeshStandardMaterial
  }
}

export function Model(props: React.ComponentProps<'group'>) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials } = useGLTF('/models/zuvy-baby-with-hair1-transformed.glb') as unknown as GLTFResult
  const { animations } = useFBX('/models/dancing-twerk-no-coat.fbx')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    if (actions && animations.length > 0) {
      const actionName = animations[0].name
      actions[actionName]?.reset().fadeIn(0.5).play()
    }
  }, [actions, animations])

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.eyebrow002.geometry} material={materials['Material.003']} position={[3.935, 6.209, 5.397]} rotation={[-Math.PI, 0, 0]} scale={0.1} />
      <mesh geometry={nodes.zuvera_body_v008001.geometry} material={materials['Material.001']} position={[3.9, 3.431, 4.384]} rotation={[-Math.PI, 0, 0]} scale={0.1} />
      <mesh geometry={nodes.diaper002.geometry} material={materials['diaper-texture']} position={[3.893, 2.25, 4.169]} rotation={[-Math.PI, 0, 0]} scale={[0.101, 0.106, 0.099]} />
      <mesh geometry={nodes.domyEyeBall_L_upHeadBase002.geometry} material={materials.eyeColor} position={[4.454, 5.655, 4.991]} scale={0.787} />
      <mesh geometry={nodes.domyEyeBall_R_upHeadBase002.geometry} material={materials['Material.002']} position={[3.332, 5.643, 5.004]} scale={0.787} />
      <mesh geometry={nodes.Object_3001.geometry} material={materials.BodyB_mat} position={[3.892, 6.439, 4.215]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/models/zuvy-baby-with-hair1-transformed.glb')
useFBX.preload('/models/dancing-twerk-no-coat.fbx')
