import { Product } from "../type/babyCareProductType";

export const babyCareProducts: Product[] = [
  // {
  //   id: 1,
  //   name: "Premium Baby Lotion",
  //   rating: 4.8,
  //   reviews: 245,
  //   image: "/images/diaper/diaper2.png",
  //   category: "Baby Lotion",
  //   inStock: true,
  //   variants: [
  //     { id: 1, image: "/images/diaper/diaper2.png", color: "White" },
  //     { id: 2, image: "/images/diaper/diaper.png", color: "Cream" },
  //   ],
  // },
  {
    id: 1,
    name: "Supreme Diapers & Pants",
    rating: 4.8,
    reviews: 245,
    image: "/images/diaper/diaper2.png",
    category: "Baby Diaper",
    inStock: true,
    variants: [
      { id: 1, image: "/images/diaper/diaper2.png", size: "M", weight: "4-10" },
      { id: 2, image: "/images/diaper/diaper.png", size: "L", weight: "9-14" },
      {
        id: 3,
        image: "/images/diaper/diaper2.png",
        size: "XL",
        weight: "12-17",
      },
      {
        id: 4,
        image: "/images/diaper/diaper2.png",
        size: "XXL",
        weight: ">15",
      },
    ],
  },
  {
    id: 2,
    name: "Premium Diapers & Pants",
    rating: 4.8,
    reviews: 245,
    image: "/images/diaper/diaper2.png",
    category: "Baby Diaper",
    inStock: true,
    variants: [
      { id: 1, image: "/images/diaper/diaper2.png", size: "NB" },
      { id: 2, image: "/images/diaper/diaper2.png", size: "S", weight: "3-6" },
      { id: 3, image: "/images/diaper/diaper.png", size: "M", weight: "4-10" },
      {
        id: 4,
        image: "/images/diaper/diaper2.png",
        size: "L",
        weight: "9-14",
      },
      {
        id: 5,
        image: "/images/diaper/diaper2.png",
        size: "XL",
        weight: "13-18",
      },
      {
        id: 6,
        image: "/images/diaper/diaper2.png",
        size: "XXL",
        weight: "16-21",
      },
    ],
  },
  {
    id: 3,
    name: "Feather Diaper Tape",
    rating: 4.8,
    reviews: 245,
    image: "/images/diaper/diaper2.png",
    category: "Baby Diaper",
    inStock: true,
    variants: [
      { id: 1, image: "/images/diaper/diaper2.png", size: "NB", weight: "<5" },
      { id: 2, image: "/images/diaper/diaper2.png", size: "S", weight: "3-6" },
    ],
  },
  {
    id: 4,
    name: "Value Diapers & Pants",
    rating: 4.8,
    reviews: 245,
    image: "/images/diaper/diaper2.png",
    category: "Baby Diaper",
    inStock: true,
    variants: [
      { id: 1, image: "/images/diaper/diaper2.png", size: "NB" },
      { id: 2, image: "/images/diaper/diaper2.png", size: "S", weight: "3-6" },
      { id: 3, image: "/images/diaper/diaper.png", size: "M", weight: "4-10" },
      {
        id: 4,
        image: "/images/diaper/diaper2.png",
        size: "L",
        weight: "9-14",
      },
      {
        id: 5,
        image: "/images/diaper/diaper2.png",
        size: "XL",
        weight: "13-18",
      },
      {
        id: 6,
        image: "/images/diaper/diaper2.png",
        size: "XXL",
        weight: "16-21",
      },
    ],
  },
  {
    id: 5,
    name: "Moisturising Tissue",
    rating: 4.6,
    reviews: 156,
    image: "/images/diaper/diaper.png",
    category: "Cotton Tissue",
    inStock: true,
  },
  {
    id: 6,
    name: "Value Wet Wipes",
    rating: 4.6,
    reviews: 156,
    image: "/images/diaper/diaper.png",
    category: "Wipes",
    inStock: true,
  },
];
